freeswitch soft nofile 500000
freeswitch hard nofile 500000
freeswitch soft nproc 20000
freeswitch hard nproc 20000
freeswitch soft rtprio 89
freeswitch hard rtprio 89
freeswitch soft nice -10
freeswitch hard nice -10
